### PR TITLE
feat: Filter ultralytics detection by class

### PR DESCRIPTION
**Pull request by borderlineinteractive**
Hi!

I created this pull request to add the feature that I suggested in issue #376:

https://github.com/Bing-su/adetailer/issues/376

This feature adds the ability to apply inpainting on specific types of objects identified by Yolo v8. I tested this with the COCO and with the Open image v7 trained yolo v8 networks: 

https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt

https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n-oiv7.pt

And it works very well for the wide range of objects that are recognized by these networks. The code simply adds a slider "Class to detect" to set which object to use. In the default 0 position it jut works as usual by recognising the first object.

### CODE REVIEW

**Comment by Bing-su** [comment]
Thanks for the PR. It seems like there are a few more things to consider, so I'll give it some more thought.

**Comment by Toad8787** [comment]
I had the same question as https://github.com/Bing-su/adetailer/issues/376.  If this works or not, this type of answer is exactly what I was looking for and I hope it gets added.

Like a fool I started training a yolo model for any and all faces.  Then I realized there are 2 problems:
- there is enough of a distinct different between realistic animals and realistic humans that the confidence level of the model plummets when you introduce realistic and cartoony/anime versions of all faces.
- the user might be trying to generate an image of more than one type of creature, but if I found all the faces, then finding them both is a mess of making sure the prompt is written for the specific image generation of the one found first and the one found second, etc.

So then I started the painstaking process of adding specific classes to each type of face.  As I am the swing of it, though, I realize it doesn't matter because we can't differentiate between classes.

Any which way it's my fault, but the use case of having one larger database like **borderlineinteractive** says sounds very useful

**Comment by Toad8787** [comment]
> Thanks for the PR. It seems like there are a few more things to consider, so I'll give it some more thought.

Is there an update on this feature request? I would really like to see this happen.

**Comment by borderlineinteractive** [comment]
Until the pull request is merged to the main branch you can try the fork that I made, which includes this feature:

https://github.com/borderlineinteractive/adetailer

I recently updated it - right now it is only 3 days behind the main repository.

**Pull request merged**
