### PR TITLE
Add "-hd" ending for models with higher resolution

### PR DESCRIPTION
**Pull request by Anzhc**
Add recognition of models ending with "-hd.pt". This will change resolution to 1024, and turn retina masks on.

### CODE REVIEW

**Comment by Anzhc** [comment]
Was training YOLO model for eyes detailing and control, that creates precise masks. For XL models 640 resolution is not enough for that task, so i looked into how to distinguish needs of particular models for higher detection resolution and precise masking.

Came up with this, it works, but im not gonna lie, i know little to nothing about code, and this solution is just a temporary patch at most. I probably inserted things where i shouldn't, but i checked if normal models and -hd models work, and they do, so idk(or rather fixed it after breaking at first, lol).
Would love to see such checks added, or sliders for YOLO controls like prediction size, IOU, retina, etc. right in UI in future.

Here is what 640 non-retina vs 1024 retina masking looks like at medium distance gen on XL
изображение

**Comment by Bing-su** [comment]
The option to specify retina_masks seems to be fine.

But think about it: adetailer uses the generated mask image with dilation by default. I doubt that very accurate detection would be meaningful in this process.

Anyway, this PR is unacceptable because it causes a error in the normal model.

**Comment by Anzhc** [comment]
By default yeah, for that model i turn off erosion/expansion of masks, and 4px blend is good, and it actually really fun to use, because you can inpaint each eye with individual prompt :D

Do you have any pointers how i could work around issue you've found? Which models error out specifically? I swear i did try to run yolo face and then my model with that change, and they worked e-e

To be sure, i did run every base model, including -world, right now, after running -hd model(and running -hd model after that), and they all worked, i did not encounter any errors

изображение

**Comment by Anzhc** [comment]
Yes, i totally agree, just not adept with code enough to figure that part out on my own yet, but i'll look around and maybe will understand later

**Pull request closed without merging**
