### PR TITLE
feat: Save image masks for later processing 

### PR DESCRIPTION
**Pull request by PhytoEpidemic**
Added option to save the mask and skip processing the image.

This can be used along side "Skip img2img" to create a mask for an image without doing anything else, making it very quick to extract masks from a batch of images.

One quirk if useing with "Skip img2img" is that if you have the img2img settings set to "Resize by" it will use lots of vram and slow down the process significantly. Recommend to use "Resize to" and just leave it at 512x512, it will not effect the mask size.

Also recommend to set your "File format for images" to the same as your input images as this will also speed things up a lot.

### CODE REVIEW

**Comment by Bing-su** [comment]
Thanks for the PR. May I ask what the purpose of this PR is?

**Comment by PhytoEpidemic** [comment]
The main thing I use it for is extracting masks from folders of images and then useing the masks to crop the images down to the subject. For example, if I want a bunch of cropped photos of hands for training a hand inpainting model. This is ideal for making a lora for adetailer because you are aligning the lora with whatever subject detection model you are useing. The reason we just create the mask and don't crop the image outright is because cropping externally (with PowerShell or something) is faster and can have the exact size of the cropped area adjusted as needed.

**Comment by Bing-su** [comment]
If that's what you're looking for, try using `ultralytics` directly from the CLI.
https://github.com/ultralytics/ultralytics/issues/1376
I don't want to add features that very few users will use right now.

**Comment by PhytoEpidemic** [comment]
Thanks for the recommendation. That might be something I do in the future but for now that looks like a lot of extra work. The point was to have it built into the webui in an easier to use fashion. There is other extension that do this already but they are made poorly and require extra setup. Adetailer just seems to work without fail so it was my best option. I can just use my fork if you don't feel like it makes sense for the main branch.

**Pull request closed without merging**
